// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ChainMates.Server;

#nullable disable

namespace ChainMates.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260402150932_InitialRecreateWithSnakeCase")]
    partial class InitialRecreateWithSnakeCase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("chain_mates")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChainMates.Server.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email_address");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.HasKey("Id")
                        .HasName("pk_author");

                    b.ToTable("author", "chain_mates");
                });

            modelBuilder.Entity("ChainMates.Server.JoinableSegmentByAuthor", b =>
                {
                    b.Property<int>("AuthorId")
                        .HasColumnType("integer")
                        .HasColumnName("author_id");

                    b.Property<int>("SegmentId")
                        .HasColumnType("integer")
                        .HasColumnName("segment_id");

                    b.ToTable((string)null);

                    b.ToView("joinable_segment_by_author", "chain_mates");
                });

            modelBuilder.Entity("ChainMates.Server.ModeratableSegmentByAuthor", b =>
                {
                    b.Property<int>("AuthorId")
                        .HasColumnType("integer")
                        .HasColumnName("author_id");

                    b.Property<int>("SegmentId")
                        .HasColumnType("integer")
                        .HasColumnName("segment_id");

                    b.ToTable((string)null);

                    b.ToView("moderatable_segment_by_author", "chain_mates");
                });

            modelBuilder.Entity("ChainMates.Server.ModerationAssignment", b =>
                {
                    b.Property<int>("AuthorId")
                        .HasColumnType("integer")
                        .HasColumnName("author_id");

                    b.Property<int>("SegmentId")
                        .HasColumnType("integer")
                        .HasColumnName("segment_id");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_closed");

                    b.HasKey("AuthorId", "SegmentId")
                        .HasName("pk_moderation_assignment");

                    b.HasIndex("SegmentId")
                        .HasDatabaseName("ix_moderation_assignment_segment_id");

                    b.ToTable("moderation_assignment", "chain_mates");
                });

            modelBuilder.Entity("ChainMates.Server.Segment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer")
                        .HasColumnName("author_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<int?>("PreviousSegmentId")
                        .HasColumnType("integer")
                        .HasColumnName("previous_segment_id");

                    b.Property<int>("SegmentStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("segment_status_id");

                    b.Property<int>("StoryId")
                        .HasColumnType("integer")
                        .HasColumnName("story_id");

                    b.HasKey("Id")
                        .HasName("pk_segment");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_segment_author_id");

                    b.HasIndex("PreviousSegmentId")
                        .HasDatabaseName("ix_segment_previous_segment_id");

                    b.HasIndex("SegmentStatusId")
                        .HasDatabaseName("ix_segment_segment_status_id");

                    b.HasIndex("StoryId")
                        .HasDatabaseName("ix_segment_story_id");

                    b.ToTable("segment", "chain_mates");
                });

            modelBuilder.Entity("ChainMates.Server.SegmentStatusEnum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.HasKey("Id")
                        .HasName("pk_segment_status");

                    b.ToTable("segment_status", "chain_mates");
                });

            modelBuilder.Entity("ChainMates.Server.SegmentTrace", b =>
                {
                    b.Property<int>("EarlierSegmentAuthorId")
                        .HasColumnType("integer")
                        .HasColumnName("earlier_segment_author_id");

                    b.Property<int>("EarlierSegmentContent")
                        .HasColumnType("integer")
                        .HasColumnName("earlier_segment_content");

                    b.Property<int>("EarlierSegmentId")
                        .HasColumnType("integer")
                        .HasColumnName("earlier_segment_id");

                    b.Property<int>("FinalSegmentId")
                        .HasColumnType("integer")
                        .HasColumnName("final_segment_id");

                    b.Property<int>("FinalSegmentStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("final_segment_status_id");

                    b.Property<int>("FinalUserId")
                        .HasColumnType("integer")
                        .HasColumnName("final_user_id");

                    b.ToTable((string)null);

                    b.ToView("segment_trace", "chain_mates");
                });

            modelBuilder.Entity("ChainMates.Server.Story", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer")
                        .HasColumnName("author_id");

                    b.Property<bool?>("IsItMature")
                        .HasColumnType("boolean")
                        .HasColumnName("is_it_mature");

                    b.Property<int?>("MaxBranches")
                        .HasColumnType("integer")
                        .HasColumnName("max_branches");

                    b.Property<int?>("MaxSegmentLength")
                        .HasColumnType("integer")
                        .HasColumnName("max_segment_length");

                    b.Property<int?>("MaxSegments")
                        .HasColumnType("integer")
                        .HasColumnName("max_segments");

                    b.Property<int?>("MinSegmentLength")
                        .HasColumnType("integer")
                        .HasColumnName("min_segment_length");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_story");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_story_author_id");

                    b.ToTable("story", "chain_mates");
                });

            modelBuilder.Entity("ChainMates.Server.ModerationAssignment", b =>
                {
                    b.HasOne("ChainMates.Server.Author", "Author")
                        .WithMany("ModerationAssignments")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_moderation_assignment_author_author_id");

                    b.HasOne("ChainMates.Server.Segment", "Segment")
                        .WithMany("ModerationAssignments")
                        .HasForeignKey("SegmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_moderation_assignment_segment_segment_id");

                    b.Navigation("Author");

                    b.Navigation("Segment");
                });

            modelBuilder.Entity("ChainMates.Server.Segment", b =>
                {
                    b.HasOne("ChainMates.Server.Author", "Author")
                        .WithMany("Segments")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_segment_author_author_id");

                    b.HasOne("ChainMates.Server.Segment", "PreviousSegment")
                        .WithMany("FollowingSegments")
                        .HasForeignKey("PreviousSegmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_segment_segment_previous_segment_id");

                    b.HasOne("ChainMates.Server.SegmentStatusEnum", "SegmentStatusEnum")
                        .WithMany("Segments")
                        .HasForeignKey("SegmentStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_segment_segment_status_segment_status_id");

                    b.HasOne("ChainMates.Server.Story", "Story")
                        .WithMany("Segments")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_segment_story_story_id");

                    b.Navigation("Author");

                    b.Navigation("PreviousSegment");

                    b.Navigation("SegmentStatusEnum");

                    b.Navigation("Story");
                });

            modelBuilder.Entity("ChainMates.Server.Story", b =>
                {
                    b.HasOne("ChainMates.Server.Author", "Author")
                        .WithMany("Stories")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_story_author_author_id");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("ChainMates.Server.Author", b =>
                {
                    b.Navigation("ModerationAssignments");

                    b.Navigation("Segments");

                    b.Navigation("Stories");
                });

            modelBuilder.Entity("ChainMates.Server.Segment", b =>
                {
                    b.Navigation("FollowingSegments");

                    b.Navigation("ModerationAssignments");
                });

            modelBuilder.Entity("ChainMates.Server.SegmentStatusEnum", b =>
                {
                    b.Navigation("Segments");
                });

            modelBuilder.Entity("ChainMates.Server.Story", b =>
                {
                    b.Navigation("Segments");
                });
#pragma warning restore 612, 618
        }
    }
}
