// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ChainMates.Server;

#nullable disable

namespace ChainMates.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260412223151_FixCommentSubTypeTables")]
    partial class FixCommentSubTypeTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("chain_mates")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChainMates.Server.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email_address");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.HasKey("Id")
                        .HasName("pk_author");

                    b.ToTable("author", "chain_mates");
                });

            modelBuilder.Entity("ChainMates.Server.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer")
                        .HasColumnName("author_id");

                    b.Property<int?>("CommentCommentCommentId")
                        .HasColumnType("integer")
                        .HasColumnName("comment_comment_comment_id");

                    b.Property<int?>("CommentCommentCommentTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("comment_comment_comment_type_id");

                    b.Property<int>("CommentStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("comment_status_id");

                    b.Property<int>("CommentTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("comment_type_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<int?>("SegmentCommentCommentId")
                        .HasColumnType("integer")
                        .HasColumnName("segment_comment_comment_id");

                    b.Property<int?>("SegmentCommentCommentTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("segment_comment_comment_type_id");

                    b.Property<int?>("StoryCommentCommentId")
                        .HasColumnType("integer")
                        .HasColumnName("story_comment_comment_id");

                    b.Property<int?>("StoryCommentCommentTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("story_comment_comment_type_id");

                    b.HasKey("Id")
                        .HasName("pk_comment");

                    b.HasAlternateKey("Id", "CommentTypeId")
                        .HasName("ak_comment_id_comment_type_id");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_comment_author_id");

                    b.HasIndex("CommentStatusId")
                        .HasDatabaseName("ix_comment_comment_status_id");

                    b.HasIndex("CommentTypeId")
                        .HasDatabaseName("ix_comment_comment_type_id");

                    b.HasIndex("CommentCommentCommentId", "CommentCommentCommentTypeId")
                        .HasDatabaseName("ix_comment_comment_comment_comment_id_comment_comment_comment_");

                    b.HasIndex("SegmentCommentCommentId", "SegmentCommentCommentTypeId")
                        .HasDatabaseName("ix_comment_segment_comment_comment_id_segment_comment_comment_");

                    b.HasIndex("StoryCommentCommentId", "StoryCommentCommentTypeId")
                        .HasDatabaseName("ix_comment_story_comment_comment_id_story_comment_comment_type");

                    b.ToTable("comment", "chain_mates");
                });

            modelBuilder.Entity("ChainMates.Server.CommentComment", b =>
                {
                    b.Property<int>("CommentId")
                        .HasColumnType("integer")
                        .HasColumnName("comment_id");

                    b.Property<int>("CommentTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("comment_type_id");

                    b.Property<int>("ParentCommentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_comment_id");

                    b.HasKey("CommentId", "CommentTypeId")
                        .HasName("pk_comment_comment");

                    b.ToTable("comment_comment", "chain_mates");
                });

            modelBuilder.Entity("ChainMates.Server.CommentStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.HasKey("Id")
                        .HasName("pk_comment_status");

                    b.ToTable("comment_status", "chain_mates");
                });

            modelBuilder.Entity("ChainMates.Server.CommentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.HasKey("Id")
                        .HasName("pk_comment_type");

                    b.ToTable("comment_type", "chain_mates");
                });

            modelBuilder.Entity("ChainMates.Server.JoinableSegmentByAuthor", b =>
                {
                    b.Property<int>("AuthorId")
                        .HasColumnType("integer")
                        .HasColumnName("author_id");

                    b.Property<int>("SegmentId")
                        .HasColumnType("integer")
                        .HasColumnName("segment_id");

                    b.ToTable((string)null);

                    b.ToView("joinable_segment_by_author", "chain_mates");
                });

            modelBuilder.Entity("ChainMates.Server.ModeratableSegmentByAuthor", b =>
                {
                    b.Property<int>("AuthorId")
                        .HasColumnType("integer")
                        .HasColumnName("author_id");

                    b.Property<int>("SegmentId")
                        .HasColumnType("integer")
                        .HasColumnName("segment_id");

                    b.ToTable((string)null);

                    b.ToView("moderatable_segment_by_author", "chain_mates");
                });

            modelBuilder.Entity("ChainMates.Server.ModerationAssignment", b =>
                {
                    b.Property<int>("AuthorId")
                        .HasColumnType("integer")
                        .HasColumnName("author_id");

                    b.Property<int>("SegmentId")
                        .HasColumnType("integer")
                        .HasColumnName("segment_id");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_closed");

                    b.HasKey("AuthorId", "SegmentId")
                        .HasName("pk_moderation_assignment");

                    b.HasIndex("SegmentId")
                        .HasDatabaseName("ix_moderation_assignment_segment_id");

                    b.ToTable("moderation_assignment", "chain_mates");
                });

            modelBuilder.Entity("ChainMates.Server.Segment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer")
                        .HasColumnName("author_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<int?>("PreviousSegmentId")
                        .HasColumnType("integer")
                        .HasColumnName("previous_segment_id");

                    b.Property<int>("SegmentStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("segment_status_id");

                    b.Property<int>("StoryId")
                        .HasColumnType("integer")
                        .HasColumnName("story_id");

                    b.HasKey("Id")
                        .HasName("pk_segment");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_segment_author_id");

                    b.HasIndex("PreviousSegmentId")
                        .HasDatabaseName("ix_segment_previous_segment_id");

                    b.HasIndex("SegmentStatusId")
                        .HasDatabaseName("ix_segment_segment_status_id");

                    b.HasIndex("StoryId")
                        .HasDatabaseName("ix_segment_story_id");

                    b.ToTable("segment", "chain_mates");
                });

            modelBuilder.Entity("ChainMates.Server.SegmentComment", b =>
                {
                    b.Property<int>("CommentId")
                        .HasColumnType("integer")
                        .HasColumnName("comment_id");

                    b.Property<int>("CommentTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("comment_type_id");

                    b.Property<int>("ParentSegmentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_segment_id");

                    b.HasKey("CommentId", "CommentTypeId")
                        .HasName("pk_segment_comment");

                    b.HasIndex("ParentSegmentId")
                        .HasDatabaseName("ix_segment_comment_parent_segment_id");

                    b.ToTable("segment_comment", "chain_mates");
                });

            modelBuilder.Entity("ChainMates.Server.SegmentStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.HasKey("Id")
                        .HasName("pk_segment_status");

                    b.ToTable("segment_status", "chain_mates");
                });

            modelBuilder.Entity("ChainMates.Server.SegmentTrace", b =>
                {
                    b.Property<int>("EarlierSegmentAuthorId")
                        .HasColumnType("integer")
                        .HasColumnName("earlier_segment_author_id");

                    b.Property<int>("EarlierSegmentContent")
                        .HasColumnType("integer")
                        .HasColumnName("earlier_segment_content");

                    b.Property<int>("EarlierSegmentId")
                        .HasColumnType("integer")
                        .HasColumnName("earlier_segment_id");

                    b.Property<int>("FinalSegmentId")
                        .HasColumnType("integer")
                        .HasColumnName("final_segment_id");

                    b.Property<int>("FinalSegmentStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("final_segment_status_id");

                    b.Property<int>("FinalUserId")
                        .HasColumnType("integer")
                        .HasColumnName("final_user_id");

                    b.ToTable((string)null);

                    b.ToView("segment_trace", "chain_mates");
                });

            modelBuilder.Entity("ChainMates.Server.Story", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer")
                        .HasColumnName("author_id");

                    b.Property<bool?>("IsItMature")
                        .HasColumnType("boolean")
                        .HasColumnName("is_it_mature");

                    b.Property<int?>("MaxBranches")
                        .HasColumnType("integer")
                        .HasColumnName("max_branches");

                    b.Property<int?>("MaxSegmentLength")
                        .HasColumnType("integer")
                        .HasColumnName("max_segment_length");

                    b.Property<int?>("MaxSegments")
                        .HasColumnType("integer")
                        .HasColumnName("max_segments");

                    b.Property<int?>("MinSegmentLength")
                        .HasColumnType("integer")
                        .HasColumnName("min_segment_length");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_story");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_story_author_id");

                    b.ToTable("story", "chain_mates");
                });

            modelBuilder.Entity("ChainMates.Server.StoryComment", b =>
                {
                    b.Property<int>("CommentId")
                        .HasColumnType("integer")
                        .HasColumnName("comment_id");

                    b.Property<int>("CommentTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("comment_type_id");

                    b.Property<int>("ParentStoryId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_story_id");

                    b.HasKey("CommentId", "CommentTypeId")
                        .HasName("pk_story_comment");

                    b.HasIndex("ParentStoryId")
                        .HasDatabaseName("ix_story_comment_parent_story_id");

                    b.ToTable("story_comment", "chain_mates");
                });

            modelBuilder.Entity("ChainMates.Server.Comment", b =>
                {
                    b.HasOne("ChainMates.Server.Author", "Author")
                        .WithMany("Comments")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_comment_author_author_id");

                    b.HasOne("ChainMates.Server.CommentStatus", "CommentStatus")
                        .WithMany("Comments")
                        .HasForeignKey("CommentStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_comment_comment_status_comment_status_id");

                    b.HasOne("ChainMates.Server.CommentType", "CommentType")
                        .WithMany("Comments")
                        .HasForeignKey("CommentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_comment_comment_type_comment_type_id");

                    b.HasOne("ChainMates.Server.CommentComment", null)
                        .WithMany("ChildComments")
                        .HasForeignKey("CommentCommentCommentId", "CommentCommentCommentTypeId")
                        .HasConstraintName("fk_comment_comment_comment_comment_comment_comment_id_comment_");

                    b.HasOne("ChainMates.Server.SegmentComment", null)
                        .WithMany("ChildComments")
                        .HasForeignKey("SegmentCommentCommentId", "SegmentCommentCommentTypeId")
                        .HasConstraintName("fk_comment_segment_comment_segment_comment_comment_id_segment_");

                    b.HasOne("ChainMates.Server.StoryComment", null)
                        .WithMany("ChildComments")
                        .HasForeignKey("StoryCommentCommentId", "StoryCommentCommentTypeId")
                        .HasConstraintName("fk_comment_story_comment_story_comment_comment_id_story_commen");

                    b.Navigation("Author");

                    b.Navigation("CommentStatus");

                    b.Navigation("CommentType");
                });

            modelBuilder.Entity("ChainMates.Server.CommentComment", b =>
                {
                    b.HasOne("ChainMates.Server.Comment", "ParentComment")
                        .WithMany("ChildComments")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_comment_comment_comment_comment_id");

                    b.HasOne("ChainMates.Server.Comment", "Comment")
                        .WithOne("CommentComment")
                        .HasForeignKey("ChainMates.Server.CommentComment", "CommentId", "CommentTypeId")
                        .HasPrincipalKey("ChainMates.Server.Comment", "Id", "CommentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_comment_comment_comment_comment_id_comment_type_id");

                    b.Navigation("Comment");

                    b.Navigation("ParentComment");
                });

            modelBuilder.Entity("ChainMates.Server.ModerationAssignment", b =>
                {
                    b.HasOne("ChainMates.Server.Author", "Author")
                        .WithMany("ModerationAssignments")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_moderation_assignment_author_author_id");

                    b.HasOne("ChainMates.Server.Segment", "Segment")
                        .WithMany("ModerationAssignments")
                        .HasForeignKey("SegmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_moderation_assignment_segment_segment_id");

                    b.Navigation("Author");

                    b.Navigation("Segment");
                });

            modelBuilder.Entity("ChainMates.Server.Segment", b =>
                {
                    b.HasOne("ChainMates.Server.Author", "Author")
                        .WithMany("Segments")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_segment_author_author_id");

                    b.HasOne("ChainMates.Server.Segment", "PreviousSegment")
                        .WithMany("FollowingSegments")
                        .HasForeignKey("PreviousSegmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_segment_segment_previous_segment_id");

                    b.HasOne("ChainMates.Server.SegmentStatus", "SegmentStatus")
                        .WithMany("Segments")
                        .HasForeignKey("SegmentStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_segment_segment_status_segment_status_id");

                    b.HasOne("ChainMates.Server.Story", "Story")
                        .WithMany("Segments")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_segment_story_story_id");

                    b.Navigation("Author");

                    b.Navigation("PreviousSegment");

                    b.Navigation("SegmentStatus");

                    b.Navigation("Story");
                });

            modelBuilder.Entity("ChainMates.Server.SegmentComment", b =>
                {
                    b.HasOne("ChainMates.Server.Segment", "ParentSegment")
                        .WithMany("Comments")
                        .HasForeignKey("ParentSegmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_segment_comment_segment_parent_segment_id");

                    b.HasOne("ChainMates.Server.Comment", "Comment")
                        .WithOne("SegmentComment")
                        .HasForeignKey("ChainMates.Server.SegmentComment", "CommentId", "CommentTypeId")
                        .HasPrincipalKey("ChainMates.Server.Comment", "Id", "CommentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_segment_comment_comment_comment_id_comment_type_id");

                    b.Navigation("Comment");

                    b.Navigation("ParentSegment");
                });

            modelBuilder.Entity("ChainMates.Server.Story", b =>
                {
                    b.HasOne("ChainMates.Server.Author", "Author")
                        .WithMany("Stories")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_story_author_author_id");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("ChainMates.Server.StoryComment", b =>
                {
                    b.HasOne("ChainMates.Server.Story", "ParentStory")
                        .WithMany("Comments")
                        .HasForeignKey("ParentStoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_story_comment_story_parent_story_id");

                    b.HasOne("ChainMates.Server.Comment", "Comment")
                        .WithOne("StoryComment")
                        .HasForeignKey("ChainMates.Server.StoryComment", "CommentId", "CommentTypeId")
                        .HasPrincipalKey("ChainMates.Server.Comment", "Id", "CommentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_story_comment_comment_comment_id_comment_type_id");

                    b.Navigation("Comment");

                    b.Navigation("ParentStory");
                });

            modelBuilder.Entity("ChainMates.Server.Author", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("ModerationAssignments");

                    b.Navigation("Segments");

                    b.Navigation("Stories");
                });

            modelBuilder.Entity("ChainMates.Server.Comment", b =>
                {
                    b.Navigation("ChildComments");

                    b.Navigation("CommentComment");

                    b.Navigation("SegmentComment");

                    b.Navigation("StoryComment");
                });

            modelBuilder.Entity("ChainMates.Server.CommentComment", b =>
                {
                    b.Navigation("ChildComments");
                });

            modelBuilder.Entity("ChainMates.Server.CommentStatus", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("ChainMates.Server.CommentType", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("ChainMates.Server.Segment", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("FollowingSegments");

                    b.Navigation("ModerationAssignments");
                });

            modelBuilder.Entity("ChainMates.Server.SegmentComment", b =>
                {
                    b.Navigation("ChildComments");
                });

            modelBuilder.Entity("ChainMates.Server.SegmentStatus", b =>
                {
                    b.Navigation("Segments");
                });

            modelBuilder.Entity("ChainMates.Server.Story", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Segments");
                });

            modelBuilder.Entity("ChainMates.Server.StoryComment", b =>
                {
                    b.Navigation("ChildComments");
                });
#pragma warning restore 612, 618
        }
    }
}
